### ISSUE TITLE
Unable to run provide-cli

### ISSUE THREAD

**Issue by ashlinsaj** [provideplatform/provide-cli#14]
Make install command is throwing an Error "undefined io.Discard" at github.com/provideplatform/provide-go/pgrok/tunnel.go :378:12

**Comment by skosito** [comment]
@ashlinsaj which go version are you using? I tried to reproduce this locally with 1.16.3 and it is working fine, maybe you need to update it?

**Comment by coolbreeze84** [comment]
> Make install command is throwing an Error "undefined io.Discard" at github.com/provideplatform/provide-go/pgrok/tunnel.go :378:12

That error will occur if you're using the wrong version of go. If you installed go via your OS then you'll need to download and install it manually.

**Comment by ashlinsaj** [comment]
> @ashlinsaj which go version are you using? I tried to reproduce this locally with 1.16.3 and it is working fine, maybe you need to update it? You will def need 1.16.x for this to work, please try to update to 1.16.x, I am not sure if the rest of the stack is optimized for latest go version yet.

Thanks the make install worked by using 1.16.3.but on creating user I get the following error
![IMG-20210917-WA0002](https://user-images.githubusercontent.com/45759808/133733179-f7313fcb-6fc6-4afa-95f5-d9e6aed5b696.jpg)

**Comment by djones0** [comment]
@ashlinsaj Could you try running it again? We're having trouble reproducing this issue.

**Comment by ashlinsaj** [comment]
> @ashlinsaj Could you try running it again? We're having trouble reproducing this issue.

Tried running it again same issue exist
nil response

**Comment by skosito** [comment]
@ashlinsaj could you please send more repro details, some of questions that can help:
- do you have latest dev?
- what happens if you authenticate with this user? (prvd authenticate)
- did you already create user with same email and pwd before and now trying to create it again? is there a same error if try with some other email?
- "First Name" is the only field that doesn't have check mark on the left, wonder if that might have something to do with this, but i don't have linux to try and repro this on linux unfortunately, might be cli linux specific issues...

**Comment by ashlinsaj** [comment]
Authentication fails with this user.I tried to create new user which
doesn't exist already.I executed by cloning the latest repo

**Comment by skosito** [comment]
@ashlinsaj try maybe `make build` which will also do clean and try `make install` again.. i will also check a bit,couple of us tried and could not reproduce it

**Comment by ashlinsaj** [comment]
> @ashlinsaj try maybe `make build` which will also do clean and try `make install` again.. i will also check a bit,couple of us tried and could not reproduce it

Thanks for your response.Tried the build and install again.but no luck.tried the same in windows.The "export" commands given in the provide-cli are linux specific,so had to replace with "set".Is this the right way to do or are you using the linux subsystem

**Comment by ashlinsaj** [comment]
> @ashlinsaj try maybe `make build` which will also do clean and try `make install` again.. i will also check a bit,couple of us tried and could not reproduce it

Hi now it's working.thanks for all your responses.

**Comment by ashlinsaj** [comment]
User creation and authentication successful
