### ISSUE TITLE
`prvdnetwork` CLI commands

### ISSUE THREAD

**Issue by zacparker41** [provideplatform/provide-cli#29]
`prvdnetwork authenticate`
`prvdnetwork vaults`
--init
--keys
--list
`prvdnetwork node`
--start 
---full
---validator
--stop
--list
--delete
`prvdnetwork governance`
--propose
---startdate/time
---enddate/time
---summary
---url (for additional info)
--vote
---proposal
----id or defaults to latest
---confirm
---reject
`prvdnetwork accounts`
--create
--update
--list

**Comment by kthomas** [comment]
This commit restructured the packaging within this repo to accommodate building `prvd` and `prvdnetwork` binaries...

https://github.com/provideplatform/provide-cli/commit/4ff43d0dff550fe7c61fb571b440e6d46c0ffa7a
